name: Release
on:
  push:
    branches: [ master ]
jobs:
  build:
    env:
      configuration: Release
      output: output
      suffix: ${{ format('master.{0}', github.run_number) }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      id: checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      id: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache packages
      id: cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    - name: Restore dependencies
      id: restore
      run: dotnet restore --use-lock-file --packages ~/.nuget/packages
    - name: Build solution
      id: build
      run: dotnet build --no-restore -c $configuration
    - name: Test solution
      id: test
      run: dotnet test --no-build -c $configuration --verbosity normal
    - name: Run Generator
      id: run
      run: dotnet run --no-build --project SciNet.Generator $output
    - name: Generate NuGet package
      id: pack
      run: dotnet pack SciNet --no-build -c $configuration --version-suffix $suffix --output $output
    - name: Upload NuGet
      id: upload-nuget
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: output/**.nupkg
