name: Development Release
on:
  push:
    branches: [ develop ]
jobs:
  generate:
    name: Generate Development Release
    runs-on: ubuntu-latest
    env:
      prefix: 0.1.0
      tag: development
    steps:
    - id: development-checkout
      name: Checkout latest develop commit
      uses: actions/checkout@v2
      
    - id: development-setup
      name: Configure .NET build tools
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - id: development-cache
      name: Download cached NuGet packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      
    - id: development-generate
      name: Generate release artifacts
      uses: ./.github/actions/generate-release
      with:
        prerelease: true
        name: SciNet
        version: ${{ env.prefix }}
        suffix: ${{ format('-{0}.{1}', env.tag, github.run_number) }}
        source: github
        key: ${{ secrets.GITHUB_TOKEN }}
        
    - id: development-release
      name: Create GitHub release
      uses: ncipollo/release-action@v1
      env:
        release: ${{ format('{0}{1}.{0}', env.prefix, env.tag, github.run_number) }}
      with:
        prerelease: true
        name: ${{ env.release }}
        tag: ${{ env.release }}
        token: ${{ secrets.GITHUB_TOKEN }}
