name: Stable Release
on:
  push:
    tags: [ '*.*.*' ]
jobs:
  generate:
    name: Generate Stable Release
    runs-on: ubuntu-latest
    steps:
    - id: stable-checkout
      name: Checkout tag commit
      uses: actions/checkout@v2
    - id: stable-release
      name: Generate release artifacts
      uses: ./.github/actions/generate-release
      with:
        name: SciNet
        version: ${{ github.ref }}
        prerelease: false
        source: github
        key: ${{ secrets.GITHUB_TOKEN }}