name: Development Release
on:
  push:
    branches: [ develop ]
jobs:
  generate:
    name: Generate Development Release
    runs-on: ubuntu-latest
    steps:
    - id: development-checkout
      name: Checkout latest develop commit
      uses: actions/checkout@v2
      
    - id: development-setup
      name: Configure .NET build tools
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - id: development-cache
      name: Download cached NuGet packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      
    - id: development-generate
      name: Generate release artifacts
      uses: ./.github/actions/generate-release
      with:
        name: SciNet
        version: 0.1.0
        suffix: ${{ format('-development.{0}', github.run_number) }}
        prerelease: true
        source: github
        key: ${{ secrets.GITHUB_TOKEN }}
