name: Candidate Release
on:
  push:
    branches: [ master ]
jobs:
  generate:
    name: Generate Candidate Release
    runs-on: ubuntu-latest
    steps:
    - id: candidate-checkout
      name: Checkout latest master commit
      uses: actions/checkout@v2
      
    - id: candidate-cache
      name: Download cached NuGet packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        
    - id: candidate-generate
      name: Generate release artifacts
      uses: ./.github/actions/generate-release
      with:
        name: SciNet
        version: 0.1.0
        suffix: ${{ format('-rc.{0}', github.run_number) }}
        prerelease: true
        source: github
        key: ${{ secrets.GITHUB_TOKEN }}
        
    - id: candidate-documentation
      name: Upload generated documentgation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: output/Documentation/